# Generated by Django 4.1.3 on 2022-11-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="email",
            new_name="user_email",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="name",
            new_name="user_name",
        ),
    ]
